### ISSUE TITLE
代码直接报错，什么原因？

### ISSUE THREAD

**Issue by sinxiao** [safe-graph/GNN-FakeNews#21]
/usr/local/bin/python3.10 /Users/mac/PycharmProjects/gnnFakeNews/gnn_model/gnn.py 
dataset>>  politifact(314)
args>>  Namespace(seed=777, device='cpu', dataset='politifact', batch_size=128, lr=0.01, weight_decay=0.01, nhid=128, dropout_ratio=0.0, epochs=35, concat=True, multi_gpu=False, feature='bert', model='sage')
Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/gnnFakeNews/gnn_model/gnn.py", line 119, in <module>
    args.num_classes = dataset.num_classes
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py", line 66, in num_classes
    return super().num_classes
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 159, in num_classes
    data_list = _get_flattened_data_list([data for data in self])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 159, in <listcomp>
    data_list = _get_flattened_data_list([data for data in self])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/data/dataset.py", line 259, in __getitem__
    data = data if self.transform is None else self.transform(data)
  File "/Users/mac/PycharmProjects/gnnFakeNews/utils/data_loader.py", line 89, in __call__
    edge_index = to_undirected(data.edge_index, data.x.size(0))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/utils/undirected.py", line 173, in to_undirected
    return coalesce(edge_index, edge_attr, num_nodes, reduce)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch_geometric/utils/coalesce.py", line 99, in coalesce
    idx[1:].mul_(num_nodes).add_(edge_index[int(sort_by_row)])
TypeError: mul_(): argument 'other' (position 1) must be Tensor, not str

Process finished with exit code 1

**Comment by YingtongDou** [comment]
The error might be due to the pyg dataloader version inconsistency. You can try to load the dataset like the [pyg official example](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/upfd.py) or install pyg 1.6.1 instead of 2.0+ version.
